language: scala

sudo: required
dist: trusty
services: docker

addons:
  apt:
    packages:
      - shellcheck

env:
  matrix:
    - RELEASE=false

before_install:
  - git fetch --tags
  - docker pull exasol/docker-db:latest
  - docker pull exasol/docker-db:6.2.7-d1

matrix:
  include:
    - jdk: oraclejdk11
      scala: 2.12.11

    - jdk: openjdk11
      scala: 2.12.11

    - jdk: oraclejdk11
      scala: 2.13.3

    - jdk: openjdk11
      scala: 2.13.3
      env: RELEASE=true

script:
  - travis_wait 30 ./scripts/ci.sh

after_success:
  - ./sbtx coveralls

before_deploy:
  - echo "Ensure assembly jar file is created for a $TRAVIS_TAG"
  - ./sbtx clean assembly
  - export JAR_VERSION=${TRAVIS_TAG}
  - echo "Jar artifact version $JAR_VERSION"
  - mkdir -p artifacts
  - cp target/scala-2.12/exasol-kafka-connector-extension-${JAR_VERSION}.jar artifacts/
  - echo "Create SHA256 Checksum"
  - cd artifacts
  - sha256sum exasol-kafka-connector-extension-${JAR_VERSION}.jar > checksum.sha256.txt
  - cd ../
  - ls -lh artifacts/

deploy:
  provider: releases
  api_key:
    secure: |-
      BZYwbVYGcA0yQ3JvC6SCB0otKsuY/u7aF/ajlLqrpAcu1w+ucs77kvceNAjPUzkhBthaagJXGfURQU71DEebjL9Nynl
      /UWHMnwx7wonbNOH3lvTSo/LTkw0XcW9rH55rJtBHmMTdzZ0EMaDTdoetuv3TNVK8Fv6j0Me55+SO+Ch3e1taLNa/3E
      mu1Z4mVL6+lEgbBMcrDM639DbhyJWpJ3dcp48U9TXoyXKvAAiW3MrSo3EvBuRDyhOeooEoT2/9R0VaFURrjEVv+dq1R
      u4SriQ/To4OcWXQGyGO09BkEJwI3qZiPY78+yysGUUl6g6DX6f/k3FcadM0cdZ5yDU3yk9FtdqELTEAXYV7e7sNfktu
      1oaEy6/gsaw+36nUjGVWC73Wu5BdJg9O0G5HL8uv5UzQRHLebecogJlTXKwJwrPkNiinvvgACtsr/++2SshFH0VOsVO
      +t9MvNBKbmU8TjtEvB0gvzqmmzjo1nyy81Dg20+Gvfc2wQAjkmDJ6YR2VblpSAxtaBrGm70MoEIKa0kTeRetEa1i4T3
      KwRFCj0pqMhpVf7HFO232FscrcLv6l1DCCGDUbn1lPZSHECYYLYVgueIUYZEQAW7t0AZDlpss7yvKsHg+bqnp/CknW3
      2i11sPvH7ggvf3CmSlN0PykCK3fErTNm9xdkYp48UyfG14=
  file:
    - artifacts/exasol-kafka-connector-extension-${JAR_VERSION}.jar
    - artifacts/checksum.sha256.txt
  skip_cleanup: true
  on:
    repo: exasol/kafka-connector-extension
    tags: true
    condition: $RELEASE = true && $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$

cache:
  directories:
    - "$HOME/.sbt/1.0"
    - "$HOME/.sbt/boot/scala*"
    - "$HOME/.sbt/cache"
    - "$HOME/.sbt/launchers"
    - "$HOME/.ivy2"
    - "$HOME/.coursier"

before_cache:
  - du -h -d 1 $HOME/.ivy2/
  - du -h -d 2 $HOME/.sbt/
  - du -h -d 4 $HOME/.coursier/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
  - find $HOME/.coursier/cache -name "*.lock" -type f -delete
